### ISSUE TITLE
目前有已经上线的app在使用吗？

### ISSUE THREAD

**Issue by Hstripe** [wxxsw/SwiftTheme#101]

**Comment by wxxsw** [comment]
这个项目最开始就是为了在线上项目中使用而设计的，曾经也在我们项目中运行过大半年的时间，后来由于产品的缘故，现在没有在使用了。

所以应该不会有更多的功能上的改进，不过会保持跟随 Swift 版本的更新，以及 bug 的修复，所以用在线上项目中应该是没有问题的。
