### ISSUE TITLE
Supporting AnimatedTabBar repo.

### ISSUE THREAD

**Issue by Maryom** [wxxsw/SwiftTheme#103]
Hello,

Thanks for your awesome repo.

I need to use this [repo.](https://github.com/AlbGarciam/AnimatedTabBar) to support Dark Mode. I tried to use `SwiftTheme` with `AnimatedTabBarAppearance.shared` but it is not working.

I also tried, `Custom Behaviors` as following:

```
NotificationCenter.default.addObserver(self, selector: #selector(updateTabBarItem), name:NSNotification.Name(rawValue: "ThemeUpdateNotification"), object: nil)

@objc func updateTabBarItem() {

        if UserDefaultsManager.shared.isNightMode {
            AnimatedTabBarAppearance.shared.backgroundColor = .red

        } else {
            AnimatedTabBarAppearance.shared.backgroundColor = .white
        }
 }
```
But I think it will need refresh because when I open/close the app it worked.

 Can you please tell me how to do it immediately without open/close the app?

**Comment by wxxsw** [comment]
Hello, I think this question is more about how to control AnimatedTabBar instead of SwiftTheme :)

**Comment by Maryom** [comment]
Thanks for your reply I appreciate it. I also asked `AnimatedTabBar`.

I think it will be awesome and useful for other people if we write a solution here.

**Comment by Maryom** [comment]
Problem solved by installing it manually instead of using pod :(

Then, simply change this line:
`tabBar.backgroundColor = AnimatedTabBarAppearance.shared.backgroundColor`

With:
`tabBar.theme_backgroundColor = ..`

Icons are another story 💪🏼
