### ISSUE TITLE
Please add support for Swift Package Dependencies 

### ISSUE THREAD

**Issue by ethanwa** [wxxsw/SwiftTheme#105]
Many people will be moving away from CocoaPods and Carthage and using Swift Package Dependencies. Please add support.

**Comment by wxxsw** [comment]
Swift Package Manager is now supported

**Comment by ethanwa** [comment]
I'm getting this error with Xcode 11:

<img width="620" alt="Screen Shot 2019-09-22 at 6 58 23 PM" src="https://user-images.githubusercontent.com/1653780/65395605-54798500-dd6b-11e9-8a6b-931ca1d73ff9.png">

**Comment by wxxsw** [comment]
I should add a new tag, you can now try to use `0.4.6`
