### ISSUE TITLE
ThemeStringAttributesPicker.pickerWithAttributes cause "signal SIGABRT" in 0.4.6 

### ISSUE THREAD

**Issue by kayelftal** [wxxsw/SwiftTheme#108]
UITextField. theme_placeholderAttributes = ThemeStringAttributesPicker.pickerWithAttributes([[NSAttributedString.Key.foregroundColor:UIColor.gray],[NSAttributedString.Key.foregroundColor:UIColor.lightGray]])
 This is working in 0.4.5, but cause "signal SIGABRT" in 0.4.6

**Comment by wxxsw** [comment]
I just tested it and it works fine.

I suggest you try clean project in xcode.

**Comment by kayelftal** [comment]
oh, after clean the project , it worked. Thanks
