### ISSUE TITLE
UINavigationBarAppearance support

### ISSUE THREAD

**Issue by evgpopov** [wxxsw/SwiftTheme#110]
Library doesn't support UINavigationBarAppearance

**Comment by kcramer** [comment]
I am working on this already but the theme is not dynamically changing for some reason.  Hopefully I will have it worked out soon.

**Comment by kcramer** [comment]
I submitted a PR to support it.  Due to changes in iOS 13 you will need to use a picker on UINavigationBar for the three new properties (i.e., standard, compact, scrollEdge) and it should dynamically update when the theme is switched.

**Comment by wxxsw** [comment]
New version `0.4.9` has been released.
