### ISSUE TITLE
 Not found string key path:

### ISSUE THREAD

**Issue by MadeBugs** [wxxsw/SwiftTheme#117]
button.theme_backgroundColor = self.infoModel.patCategory ? "Global.primaryColor" : "Global.buttonUnableColor"

求解决

**Comment by wxxsw** [comment]
你能否提供更多信息，比如你的样式文件，以及完整的错误信息。

**Comment by MadeBugs** [comment]
写三个按钮设置颜色，前两个不行，第三个行，很奇怪，时灵时不灵
<key>Global</key>
	<dict>
		<key>buttonUnableColor</key>
		<string>#757575</string>
		<key>primaryColor</key>
		<string>#FB7DDB</string>
		<key>backgroundColor</key>
		<string>#FFFFFF</string>
	</dict>

**Comment by wxxsw** [comment]
错误信息是？

**Comment by MadeBugs** [comment]
> 错误信息是？

SwiftTheme WARNING: Not found string key path: Clobal.buttonUnableColor

**Comment by wxxsw** [comment]
看起来好像你把 Global 打成了 Clobal

**Comment by MadeBugs** [comment]
> 看起来好像你把 Global 打成了 Clobal
自己傻逼了，[捂脸]

**Comment by wxxsw** [comment]
😆
