### ISSUE TITLE
如何设置纯透明

### ISSUE THREAD

**Issue by deepindo** [wxxsw/SwiftTheme#120]
作者好，

我有如下场景：
 
基类VC中默认设置一个控件的主题色组，两个色值，都是十六进制RGB格式的，有一个继承基类VC的子VC，对于该控件，不论哪个主题，都是要透明的，也就是UIColor.clear；

我看到readme文件中有RGBA格式传入的方法，就将"#ffffff00", "##ffffff00"传入，但是xcode日志处会输出：
SwiftTheme WARNING: Not convert rgba ##ffffff00 in array: ["#ffffff00", "##ffffff00"][1]

当我xcode直接运行app到手机的时候，主题切换时，显示正常，当关掉app，重新打开的时候，就有机率，显示的还是基类设置的色值组

另外我这边更加适合直接传入colors给theme_xxx，一般对于color都封装好了hexColor的方法，甚至起了便于识别的颜色名字，在readme中看到可以用类似：UIColor.yellow.cgcolor的形式传入，尝试过，会提示，无法将ThemeCGColorPicker转为ThemeColorPicker

盼回复，谢谢！

**Comment by deepindo** [comment]
补充一下，如果单纯设置theme_alpha为0,  当前控件的子控件都将无法显示，此问题，主要问题点还是在完全透明上

**Comment by wxxsw** [comment]
你好，根据错误信息可以知道 ##ffffff00 转换失败了，看起来是前面多加了一个 #

**Comment by deepindo** [comment]
哇，回复好快，这个漏掉了，失误。

那请问ThemeCGColorPicker方法的正常打开方法是什么呢？

**Comment by wxxsw** [comment]
使用 `UIColor` 还是 `CGColor` 取决于原始属性需要的是什么，如果想直接传递 Color 类型，可以这么写：
```swift
view.theme_backgroundColor = ThemeColorPicker(colors: UIColor.red, UIColor.blue)
view.layer.theme_backgroundColor = ThemeCGColorPicker(colors: UIColor.red, UIColor.blue)
view.layer.theme_backgroundColor = ThemeCGColorPicker(colors: UIColor.red.cgColor, UIColor.blue.cgColor)
```
三种方式应该都是可以的

**Comment by wxxsw** [comment]
默认的写法
```swift
view.theme_backgroundColor = ["#ffffff", "#000000"]
```
是一种通过字面量初始化的方式，方便调用，`["#ffffff", "#000000"]` 其实赋值到 `theme_backgroundColor` 时就已经是 `ThemeColorPicker` 类型

**Comment by wxxsw** [comment]
所以对于通过其它类型初始化，或者更高级的需求，可以直接通过 `ThemeColorPicker` 的其它初始化方法实现

**Comment by deepindo** [comment]
![image](https://user-images.githubusercontent.com/18132241/75861265-1e6f1f80-5e38-11ea-9319-50ae08953e25.png)
尝试过上面的方法，似乎不太行

一个是ThemeColorPicker的初始化方法参数基本都是String类型的，和UIColor类型不同；
另外一个是ThemColorPicker和ThemeCGColorPicker都是ThemePicker的子类，两个类不同，不能转换，以theme_backgroundColor为例，只属于ThemeColorPicker类型的

**Comment by deepindo** [comment]
图片上传不成功，以上说的几个情况，都尝试过，会报错

**Comment by wxxsw** [comment]
你这个应该不是最新版本，更新到最新版本就好了

**Comment by deepindo** [comment]
最新是0.5.0么
Installing SwiftTheme (0.5.0) 

我没有带版本号，和https://cocoapods.org/上也对得上

**Comment by wxxsw** [comment]
哦，上个版本可能 Cocoapods 的检查规则变了，提交 Cocoapods 的时候失败了，我又修改了一下提交了个新版本，你更新下试试
