### ISSUE TITLE
如何清除原本的theme图片设置

### ISSUE THREAD

**Issue by deepindo** [wxxsw/SwiftTheme#121]
有这样一个场景：

基类里面有一个按钮，设置的是两张默认的主题图片，以及主题文字的颜色；
某个子类里面，不显示图片，要设置成纯文字展示，原来只展示文字，当切换主题的时候，默认的题图片也会被显示出来。

请问是否有可以清除原本主题设置的，或者能达到所想要的效果的方?

**Comment by wxxsw** [comment]
设置对应的主题属性为 `nil` 即可
