### ISSUE TITLE
能否拿到ColorPicker对应的UIColor值？

### ISSUE THREAD

**Issue by zzzzzyijie** [wxxsw/SwiftTheme#122]
你好！

比如：

```
    static let backgroundColor: ThemeColorPicker = ["#FFF", "#18222D"]

```

能否拿到backgroundColor对应mode的UIColor值？
在某些场景可能需要使用UIColor去设置，比如一些第三方库 （config.color..）

（如果能使用Theme.backgroundColor.color 或 Theme.backgroundColor.hexString能拿到对应的值，那这样感觉会方便很多） 

或者有什么比较好的解决方案？

谢谢。

**Comment by wxxsw** [comment]
抱歉，回复的有点晚了

你可以这样获得 `ThemePicker` 的值：
```swift
let color = Theme.backgroundColor.value() as? UIColor
```

**Comment by zzzzzyijie** [comment]
已解决我的疑问，感谢~
