### ISSUE TITLE
CATextLayer 扩展暗黑模式

### ISSUE THREAD

**Issue by zwt369** [wxxsw/SwiftTheme#124]
项目中有用到CATextLayer使用富文本渲染，作者有计划扩展此种业务吗

**Comment by wxxsw** [comment]
理论上是可以支持的，类似对 CALayer 的支持，但会增加一些新的类型，你可以列一下具体会用到哪几个属性，我周末有空的时候加下试试。

**Comment by zwt369** [comment]
就用到了string的属性，我给换成label了
