### ISSUE TITLE
请问我能自行通过extension实现对第三方UI控件的支持吗，比如indicatorColor扩展为theme_indicatorColor

### ISSUE THREAD

**Issue by Joecao123** [wxxsw/SwiftTheme#125]

**Comment by wxxsw** [comment]
虽然不知道你所指的具体属性是什么，但例如 indicatorColor，我猜测应该只是个配置，最终也是间接设置某个视图的具体样式上，例如里面某个视图的背景色，因为是间接设置，所以你即便通过 extension 也无法控制第三方的内部逻辑，而 SwiftTheme 需要修改的是它最终设置颜色的那个位置，例如设置背景色的位置。

所以这对于使用者来说，其实很难改第三方的源码，我的建议是，你封装一下第三方 UI 控件，在封装的类中监听主题的切换，然后调用 indicatorColor 设置不同的值。

**Comment by Joecao123** [comment]
好的，回复的太快了，谢谢大佬，我尝试一下
