### ISSUE TITLE
UIButton 是否可以支援ThemeStringAttributes呢？

### ISSUE THREAD

**Issue by cimonk** [wxxsw/SwiftTheme#128]
想要可以使用A theme时 button title显示 `{黑字}abc{红字}def`
切换成B theme时 button title显示 `{白字}abc{红字}def`

请问有大佬可以教学指导吗？ (除了用一个使用theme_textAttributes的UILabel叠在UIButton上面作为显示外)
谢谢

**Comment by wxxsw** [comment]
我注意到 `UIButton` 有个 `setAttributedTitle:forState:` 方法，我觉得增加一个 `theme_setAttributedTitle:forState:` 方法是个不错的主意，只是我最近比较忙，抱歉可能要过一段时间可以加这个方法
