### ISSUE TITLE
How to Implement ThemePicker for CAGradientLayer with property: _colors ?

### ISSUE THREAD

**Issue by herotf3** [wxxsw/SwiftTheme#129]
Currently there is no common way to implement a picker for array

**Comment by wxxsw** [comment]
Example:
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/921863/91281396-9d775c00-e7ba-11ea-9c56-3d768a984eef.png">
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/921863/91281415-a2d4a680-e7ba-11ea-8318-a0cf3ff1e18b.png">
