### ISSUE TITLE
适配Swift 5.3.0

### ISSUE THREAD

**Issue by zhangshouhai** [wxxsw/SwiftTheme#131]
你好 ，因为使用了SwiftTheme ,更新了Xcode ,导致出现了这个错误（module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3 compiler），请问能否升级一次版本，做一下适配？多谢

**Comment by wxxsw** [comment]
Hi，你是使用 Cocoapods 还是 Carthage？

**Comment by zhangshouhai** [comment]
Cocoapods

**Comment by wxxsw** [comment]
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/921863/95537199-a9904380-0a1f-11eb-8145-f5c6e43aac8c.png">
我新建了一个项目，测试是可以的，你的 Xcode Command Line Tools 版本是多少？以及 SwiftTheme 版本？

**Comment by zhangshouhai** [comment]
SwiftTheme 0.5.2 、   Xcode: Version 12.0.1、Xcode Command Line Tools  :version 2373.

**Comment by zhangshouhai** [comment]
module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3 compiler: /Users/mac/Library/Developer/Xcode/DerivedData/YXDoctor-eqmbxdniplwcrmcenfgxtzngpkmc/Build/Products/Debug-iphoneos/SwiftTheme/SwiftTheme.swiftmodule/arm64-apple-ios.swiftmodule

**Comment by wxxsw** [comment]
建议你先更新 cocoapods 版本，然后执行 pod install，clean 之后重新 build 下看看。

如果上面不行，可以先删除生成的 Pods 文件夹，重新 pod install 后再编译看看。

**Comment by zhangshouhai** [comment]
好的 ，谢谢 ，我试试
