### ISSUE TITLE
[Feature]: Support color with Alpha property 

### ISSUE THREAD

**Issue by hemantgore** [wxxsw/SwiftTheme#136]
Can we have support for custom Alpha property while setting colors?
Similar to what we have for fonts to specify size!
`    "textFontRegular": "PingFangSC-Regular,30" 
`
On the same line, can we have something like:
`    "textColor": "#ECF0F1,0.6"` 

Or am I missing anything which is already available?

**Comment by wxxsw** [comment]
Please see this: https://github.com/wxxsw/SwiftTheme/issues/39

**Comment by hemantgore** [comment]
Hey @wxxsw, that was quick! 😊 
Thank You !!! 🙏
