### ISSUE TITLE
OC中如何如何像Swfit里一样用json或者plist的字面量来生成picker？

### ISSUE THREAD

**Issue by carlchou00** [wxxsw/SwiftTheme#137]
在Swift中可以如下一样来调用json或者plist文件里的值：
theme_backgroundColor = "Global.backgroundColor"

但是在OC中只能有如下方法来初始化picker：
self.theme_backgroundColor = self.contentView.theme_backgroundColor = [ThemeColorPicker pickerWithColors:@[@"#FFFFFF",@"#1F1F1F"]];

请问一下，在OC中使用plist或者json时，如何生成picker呢？

**Comment by dream5788** [comment]
同问，后来解决吗？
