### ISSUE TITLE
SwiftTheme for CGContext

### ISSUE THREAD

**Issue by iamvm05** [wxxsw/SwiftTheme#140]
Is there a provision for applying theme on any CGContext type objects?
If yes, then can you please include an extension for CGContext?

I need to apply theme to the CGContext setFillColor property.

Code Sample:

```
override func draw(in ctx: CGContext) {
     ctx.setFillColor(ColorConstants.lightsSoftGray?.cgColor ?? UIColor.lightGray.cgColor)
}

```

**Comment by wxxsw** [comment]
Sorry, CGContext does not inherit from NSObject, so it is not supported
