### ISSUE TITLE
Cannot find type 'UIControl' in scope in ThemePicker.swift line 49

### ISSUE THREAD

**Issue by ethanwa** [wxxsw/SwiftTheme#143]
I'm getting an odd Error in Xcode when I'm trying to build that I can't seem to track down. SwiftTheme has been added via SPM (version 0.6.0). I've tried re-adding the package, deleting DerivedData, and more, but I can't stop the Error from occurring when adding SwiftTheme. I've even tried SwiftTheme 0.5.5 and I have the same issue. I'm wondering if maybe it's a conflict with one of my other packages, but I am not sure. Here is the Error:

<img width="819" alt="Screen Shot 2021-02-19 at 1 16 26 AM" src="https://user-images.githubusercontent.com/1653780/108465493-1dedb580-7250-11eb-98d6-ba6059d03f96.png">

Here are the packages I use:

<img width="662" alt="Screen Shot 2021-02-19 at 1 17 42 AM" src="https://user-images.githubusercontent.com/1653780/108465573-483f7300-7250-11eb-8af4-33dbd9a256bf.png">

Any ideas on what I should look for as to what could be causing this Error in this specific part of the code? I can't help but think this is some compiler problem in Xcode 12.4. I am on an M1 Mac.

**Comment by wxxsw** [comment]
I fixed the problem and released a new version 0.6.1.
