### ISSUE TITLE
The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99.

### ISSUE THREAD

**Issue by ethanwa** [wxxsw/SwiftTheme#145]
This is happening on Xcode 12.4 using SPM:

<img width="855" alt="Screen Shot 2021-02-19 at 5 53 58 PM" src="https://user-images.githubusercontent.com/1653780/108570297-846be580-72db-11eb-8bf3-2bc6aaaf5ac2.png">

**Comment by wxxsw** [comment]
I fixed the problem and released a new version 0.6.2.
