### ISSUE TITLE
oc 如何设置渐变 theme_colors

### ISSUE THREAD

**Issue by bbtyou** [wxxsw/SwiftTheme#151]
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/48973364/123046452-b4b0c580-d42e-11eb-8169-a13ac89c3c67.png">
_gradientLayer.theme_colors = [ThemeCGColorPicker pickerWithKeyPath:_theme_path map:^CGColorRef _Nullable(NSArray *list) {
        NSMutableArray *colors = @[].mutableCopy;
        for (NSString *hex in list) {
            [colors addObject:(id)HexColor(hex).CGColor];
        }
        return [colors copy];
    }];

pickerWithKeyPath返回的是CGColorRef，而不是数组，并且设置了[UIColor redColor].CGColor也没有生效。

**Comment by NikhilGangurde** [comment]
Did you find a solution if you did can you show it?

**Comment by bbtyou** [comment]
自己监听，重新设置下。
<img width="935" alt="image" src="https://user-images.githubusercontent.com/48973364/158111108-ad63742e-d452-45b9-9a38-9fa34a8332fe.png">
