### ISSUE TITLE
如何在OC中通过theme获取Color呢

### ISSUE THREAD

**Issue by tospery** [wxxsw/SwiftTheme#156]
UIColor *color = [ThemeColorPicker pickerWithKeyPath:@"backgroundColor"].value();
报value找不到

**Comment by wxxsw** [comment]
@"#0" 改为 @"#000"

颜色至少需要表示 R、G、B 的十六进制

**Comment by wxxsw** [comment]
当前主题索引是？

**Comment by tospery** [comment]
![image](https://user-images.githubusercontent.com/3716286/141420080-27b055fe-2612-4d91-9a3d-67d795b030ff.png)
![image](https://user-images.githubusercontent.com/3716286/141420137-9bda3ecf-5c9d-412d-8c39-7c6de05d2ac5.png)

**Comment by tospery** [comment]
> 当前主题索引是 0 或者 1 吗？

只有一个主题，索引为0

**Comment by tospery** [comment]
我的需求是，获取主题的具体颜色，用在富文本中。但我发现只能拿picker，拿不到color。不知道是不是OC的原因

**Comment by wxxsw** [comment]
哦是的，OC 目前不支持获取 value

可以考虑使用 label.theme_attributedText

**Comment by wxxsw** [comment]
实例：
```oc
label.theme_attributedText = [ThemeAttributedStringPicker pickerWithKeyPath:@"backgroundColor" map:^NSAttributedString * _Nullable(id _Nullable value) {
    NSString *hex = (NSString *)value;
    UIColor *color = [[UIColor alloc] initWithRgba:hexString defaultColor:[UIColor clearColor]];
    return value;
}];
```

**Comment by tospery** [comment]
嗯嗯，明白你的意思。我有用一个三方库DZNEmptyDataSet，它通过代理方法返回NSAttributedString来展示空页面的文案。
![image](https://user-images.githubusercontent.com/3716286/141422106-d30b7106-285c-4a7a-a017-b30b07fa498a.png)
如果可以的话，希望能把value暴露给OC一下呢

**Comment by wxxsw** [comment]
因为 value 是在基类里面的，所以实际上即便暴露了，也无法返回 UIColor 类型，只能返回 id 类型。

如果 id 类型可以接受的话，可以使用 `[ThemeManager valueFor:@"keyPath"];`

**Comment by tospery** [comment]
[ThemeManager colorFor:@"primaryColor"];可以满足我的需要，谢谢。
