### ISSUE TITLE
Crash when Swift 3 @objc inference default on Swift 4 Language

### ISSUE THREAD

**Issue by ajpahlevi** [wxxsw/SwiftTheme#56]
Our project setting

> Swift Language Version : Swift 4.0
> Swift 3 @objc Inference : Default

Crash

Line 21 NSObject+Theme
`objc_setAssociatedObject(self, &themePickersKey, initValue, .OBJC_ASSOCIATION_RETAIN_NONATOMIC)`

<img width="962" alt="screen shot 2018-01-08 at 08 49 04" src="https://user-images.githubusercontent.com/29137113/34656169-d8a9b094-f450-11e7-8807-731b8c93541c.png">
<img width="287" alt="screen shot 2018-01-08 at 08 49 14" src="https://user-images.githubusercontent.com/29137113/34656172-de8ba40e-f450-11e7-826f-1e50a9236c16.png">

**Note**
Doesn't happen when Inference set to On

**Comment by wxxsw** [comment]
Sorry for the late reply, because it is a compatibility issue with the previous Swift version, it should not happen now, close.
