### ISSUE TITLE
UIBarButtonItem Appearance state

### ISSUE THREAD

**Issue by royherma** [wxxsw/SwiftTheme#69]
Is there a solution to add a theme for the `UIBarButtonItem` `UIAppearnce` state attributes, for example:

```UIBarButtonItem.appearance().setTitleTextAttributes([NSFontAttributeName: barbuttonFont], for: UIControlState.normal)```

```UIBarButtonItem.appearance().setTitleTextAttributes([NSFontAttributeName: barbuttonFont], for: UIControlState.highlighted)```

```UIBarButtonItem.appearance().setTitleTextAttributes([NSFontAttributeName: barbuttonFont], for: UIControlState.disabled)```

**Comment by kcramer** [comment]
I submitted a PR to add theme_setTitleTextAttributes for UIBarItem.  The change should be in the master branch.  It works for setting a theme on a particular UIBarButtonItem, although the button font doesn't change once the view is rendered, but does change if the view is displayed again.

However, after additional testing, I discovered it does not work with UIAppearance.  If you try to set the theme on a UIBarButtonItem via UIAppearance, it results in an NSInternalInconsistencyException.

UIBarItem and UIBarButtonItem are not UIView's and have their own UIAppearance proxy.  It appears that custom proxy does not handle this situation correctly and results in an exception being thrown which will crash your application.

I may report the issue to Apple but for now, I don't see how to make the theme support work with UIAppearance on UIBarButtonItems.

Additional Info:

Setting the theme via UIBarItem does not result in an exception but does not change the font of the buttons.  It appears you need to do it via the UIBarButtonItem's UIAppearance.

I tried adding the extension theme_setTitleTextAttributes on all combinations of UIBarItem and UIBarButtonItem but it does not change the outcome.
