### ISSUE TITLE
能否反向用过字符串拿到plist里面的颜色?

### ISSUE THREAD

**Issue by chenfengfeng** [wxxsw/SwiftTheme#75]
比如说我导航栏这样写:
navigationBar.theme_tintColor = "Global.barTextColor"

我想通过"Global.barTextColor"拿到里面对应的颜色或者拿到uicolor

可以吗?

**Comment by z234009184** [comment]
我也有同样的问题

**Comment by z234009184** [comment]
可以通过这个
[ThemeManager colorFor:@"ViewBackGroundColor"];
