### ISSUE TITLE
ThemeColorPicker feature request (nil represents default color)

### ISSUE THREAD

**Issue by grysvn** [wxxsw/SwiftTheme#86]
Would it be possible would it be to leave a color as whatever it defaults to if nil is passed in to the array literal? I searched for an issue related to this and couldn't find any that seem to be related.

**Comment by kcramer** [comment]
It would take some effort to implement as there are a variety of settings and defaults.  For some of them you cannot just unset them.  You would need to know the default colors and handle each appropriately.  Currently, the framework handles most components generically and this change would require knowing what UIKit object it is working on.

What was the motivation behind the request?

**Comment by grysvn** [comment]
I was adding in a dark-mode feature to my application and the light theme, when making it `#000000`, was lighter than a lot of the default parts of the UI. I could've probably found the default colors pretty easily, but I didn't have the time to do that for each UI element. That's what I would've thought.

Here's one thing I thought of, which would be a pretty specific special-case so I'm not saying this as a suggestion to do, but just to mention: if nil is passed in as an array element of `ThemeColorPicker`, then maybe SwiftTheme could get the color of the UI element in question and save it into the index of nil?

**Comment by leo150** [comment]
`ThemeColorPicker` doesn't have an initializer with `UIColor?` array. Why wouldn't you just declare a static function what will accept an `UIColor?` and fallback to the default color if unwrapping failed?
