### ISSUE TITLE
oc创建的工程，用cocopods集成，无法找到对应的方法

### ISSUE THREAD

**Issue by Shannon-Yang** [wxxsw/SwiftTheme#91]
oc创建的工程，用cocopods集成，#import "XXX-Swift.h"后，但是在oc里面提示没有该方法，报错，只有手动将source文件拖到项目中，才能找到对应的方法

**Comment by wxxsw** [comment]
试下 `#import <SwiftTheme/SwiftTheme-Swift.h>` 可以吗？

**Comment by Shannon-Yang** [comment]
@wxxsw 提示'SwiftTheme/SwiftTheme-Swift.h' file not found，报错，oc调用swift应该都需要#import "XXX-Swift.h"
