### ISSUE TITLE
UILabel如何设置attributedText？

### ISSUE THREAD

**Issue by Shannon-Yang** [wxxsw/SwiftTheme#97]
请问如何设置UILabel的attributedText，extension UILabel 中没有theme_titleTextAttributes这个属性，只有extension UINavigationBar才有这个属性，请问如何设置不同模式下UILabel的富文本

**Comment by wxxsw** [comment]
因为目前不支持切换 `NSAttributedString`，只能通过注册通知的方式来解决：
```
NotificationCenter.default.addObserver(
	self, 
	selector: #selector(doSomethingMethod),
	name: NSNotification.Name(rawValue: ThemeUpdateNotification), 
	object: nil
)
```
```
func doSomethingMethod() {
    if ThemeManager.currentThemeIndex == 0 {
        self.label.attributedText = ...
    } else {
        self.label.attributedText = ...
    }
}
```
我会尝试一下支持 `NSAttributedString` 的切换，你可以先使用上面的临时方案解决，或者同时设置 `label` 的 `theme_textColor`、`theme_font` 是否能解决你的需求

**Comment by Shannon-Yang** [comment]
好的，谢谢~！

**Comment by yuhongli1989** [comment]
我目前 是把作者的代码改了 让他支持富文本，自己在extension中添加了theme_setAttributedText属性

**Comment by wxxsw** [comment]
Example:
```swift
label.theme_textAttributes = [
    [.foregroundColor: UIColor.red],
    [.foregroundColor: UIColor.blue],
]
```

**Comment by HMWDavid** [comment]
> 例：
> 
> ```swift
> 标签。theme_textAttributes  = [ 
>     [。前景色： UIColor。红色]，
>     [。前景色： UIColor。蓝色]，
> ]
> ```

theme_titleTextAttributes 的再json文件中的格式如何编写

**Comment by wxxsw** [comment]
@HMWDavid 
```swift
label.theme_textAttributes = .init(keyPath: "someKeyPath") { value in
    let attributes: [NSAttributedString.Key: Any] = [:]
    // value to attributes
    return attributes
}
```
实际上就是 json 中存的数据是什么格式都可以，转换过程也由你自己来控制

**Comment by HMWDavid** [comment]
OK,感谢回复
